name: RELEASE

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - 'dev'

jobs:
  tests:
    name: Typecheck and Tests
    strategy:
      matrix:
        node-version: [ 16.17 ]
    runs-on: ${{ matrix.node-version }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Build
        run: npm run build

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Test and coverage
        run: npm run coverage
        env:
          CI: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: packages/*/coverage/cobertura-coverage.xml

      - name: Dist Packages Output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package_artifacts
          path: packages/*/dist

  pre-release:
    name: publishing version
    permissions: write-all
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev' }}
    needs: tests
    strategy:
      matrix:
        node-version: [ 16.17 ]
    runs-on: ${{ matrix.node-version }}

    steps:
      - name: Checkout Nodejs
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package_artifacts
          path: packages

      - name: Check changeset status
        run: npx changeset status --since=origin/dev

      - name: Prepare changeset
        run: npx changeset pre enter ergo

      - name: Update changeset version
        run: |
          sed -i "s/ergo/next-${{ github.sha }}/g" .changeset/pre.json
          npx changeset version
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc

        env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  

      - name: Publish changeset
        run: npx changeset publish
