name: Releae

on:
  pull_request:
    types:
      - closed
  workflow_run:
    workflows:
      - 'TEST Workflow'
    types:
      - completed

jobs:
  dummy-job:
    name: Dummy Job
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Step
        run: echo "This is a dummy job"

  release:
    name: Release Job
    needs: dummy-job
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download artifacts from "TEST Workflow"
        uses: dawidd6/action-download-artifact@v2
        with:
          name: package_artifacts
          path: packages
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Changin Version Using changeset
        run: |
          npx changeset version

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish changeset
        run: npx changeset publish
