name: SNAPSHOT_RELEASE

on:
  workflow_run:
    workflows:
      - "TEST"
    types:
      - success
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev


jobs:
  prerelease:
    name: publishing snapshot version
    permissions: write-all
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev' }}
    needs: tests
    strategy:
      matrix:
        node-version: [ 16.x , 18.x ]
    runs-on: ${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package_artifacts
          path: packages

      - name: Check changeset status
        run: npx changeset status --since=origin/dev

      - name: Prepare changeset
        run: npx changeset pre enter ergo

      - name: Update changeset version
        run: |
          sed -i "s/ergo/next-${{ github.sha }}/g" .changeset/pre.json
          npx changeset version
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  

      - name: Publish changeset
        run: npx changeset publish
