name: TEST Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev

jobs:
  tests:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build

      - name: Dist Packages Output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ergo
          path: packages/*/dist

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      # not work

      #      - name: Test
      #        run: npm run coverage
      #
      #      - name: Upload app coverage to Codecov
      #        uses: codecov/codecov-action@v2
      #        with:
      #          files: packages/*/coverage/coverage-final.json
      #          token: ${{ secrets.CODECOV_TOKEN }}
