on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Print
        run: |
          git log -1 --format="%cn"
          git log -1 --format="%ce"
